Add money command
cepave-f2e/slack-bot pull request #8
Opened 2016-09-28 13:32 UTC by chuanxd

### What? Why?
- how to use ?
    - enter message '$money' + 'CURRENCY'
    - e.g. '$money USD'

default bank `Tai Shin bank 台新銀行` 

### How was it tested?
localhost

2016-09-28 13:48 UTC, rwu823 requested changes
## \- Change`$money`  to `$currency`

2016-09-28 13:48 UTC, rwu823 commented on src/commands/money.js
> +  }
`EMOJI_MOMENY_BAG` `bankCode` `currency` 往外拉，沒必要在 function 裡

2016-09-28 13:48 UTC, rwu823 approved these changes

2016-10-08 05:07 UTC, chuanxd commented on src/commands/money.js
> +  }
@rwu823 fixed

2016-10-08 13:54 UTC, rwu823 requested changes

2016-10-08 13:54 UTC, rwu823 commented on src/commands/currency.js
> +  ZAR: 13
由 0 開始算的話，直接用 `Array` 代替就好了？

2016-10-08 13:54 UTC, rwu823 commented on src/commands/currency.js
> +  const getExchange = (bankCode, currencyNumber) => {
`getExchange` 也可拉至外部

2016-10-09 04:53 UTC, chuanxd commented on src/commands/currency.js
> +  ZAR: 13
這是 mapping 輸入幣值的字串

2016-10-09 05:00 UTC, chuanxd commented on src/commands/currency.js
> +  const getExchange = (bankCode, currencyNumber) => {
fixed @rwu823

2016-10-09 13:28 UTC, rwu823 approved these changes

2016-10-09 13:28 UTC, rwu823 commented
Nice

2016-10-09 13:28 UTC, merged